defmodule ActivityPlanner.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:participants) do
      add :company_id, :uuid
    end

    create table(:companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:participants) do
      modify :company_id,
             references(:companies,
               column: :id,
               name: "participants_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:companies) do
      add :name, :text, null: false
      add :description, :text
    end

    create table(:activity_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
      add :description, :text

      add :company_id,
          references(:companies,
            column: :id,
            name: "activity_groups_company_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :title, :text, null: false
      add :start_time, :utc_datetime_usec, null: false
      add :end_time, :utc_datetime_usec, null: false

      add :responsible_participant_id,
          references(:participants,
            column: :id,
            name: "activity_groups_responsible_participant_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :activity_group_id,
          references(:activity_groups,
            column: :id,
            name: "activity_groups_activity_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:activity_groups, "activity_groups_company_id_fkey")

    drop constraint(:activity_groups, "activity_groups_responsible_participant_id_fkey")

    drop constraint(:activity_groups, "activity_groups_activity_group_id_fkey")

    drop table(:activity_groups)

    alter table(:companies) do
      remove :description
      remove :name
    end

    drop constraint(:participants, "participants_company_id_fkey")

    alter table(:participants) do
      modify :company_id, :uuid
    end

    drop table(:companies)

    alter table(:participants) do
      remove :company_id
    end
  end
end